version: '3'
services:
  dvl:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'discord-voice-log'
    working_dir: '/root/opt/resource'
    tty: true
    volumes:
      - .:/root/opt
  psql:
    image: postgres:15
    restart: always
    container_name: postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dvl
    volumes:
      - ./init:/docker-entrypoint-initdb.d